### ISSUE TITLE
Script empties the hole hosts file :-O

### ISSUE THREAD

**Issue by berndgz** [iamqiz/bash-wsl2-host#1]
Nice idea, but I'm having trouble with the script. I'm located behind a proxy and VPN, therefore I use wsl-vpnkit. There was no entry in the hosts file for the running distribution and the Bash-wsl2-host script stuck during the Windows PowerShell process and empties the hole hosts file, that's not good.

**Comment by berndgz** [comment]
I have forked the project under https://github.com/berndgz/wsl2hosts and fixed some issues.

**Comment by iamqiz** [comment]
thanks for improving, 
actually , i appended new ip when windows hosts file  don''t have the ip name in my real bash , but  I didnt push it to github😂
your code is good, i will merge it, thanks for pr😄
